# Generated by Django 6.0.6 on 2026-06-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(blank=True, max_length=50, null=True)),
                ('nis', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(default='Aktif', max_length=20)),
            ],
            options={
                'db_table': 'peminjam_anggota',
            },
        ),
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('buku', models.CharField(max_length=255)),
                ('tgl_pinjam', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_kembali', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'peminjam',
            },
        ),
    ]
