# Generated by Django 6.0.6 on 2026-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(blank=True, max_length=255, null=True)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('penerbit', models.CharField(blank=True, max_length=255, null=True)),
                ('tahun_terbit', models.IntegerField(blank=True, null=True)),
                ('stok', models.IntegerField(default=0)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('rak', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'buku',
            },
        ),
    ]
